### ISSUE TITLE
Add Input component

### ISSUE THREAD

**Issue by LogicalAnt** [reactizard/plain-ui#34]

**Comment by minhazurrony** [comment]
@LogicalAnt bro, kindly add me on project board, can't see all the details here

**Comment by LogicalAnt** [comment]
@minhazurrony , Please check now

**Comment by LogicalAnt** [comment]
@minhazurrony 
Figma design:
https://www.figma.com/file/0IWQP2wmlANxrcf8YEZOQb/%F0%9F%A4%97--Friendly-UI-kit-(Community)?node-id=77%3A385&mode=dev
